### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by HarshDobariya79** [LJOSC/checkmark-backend#1]
### Tasks
- Add `README.md` file with project description.
- Package.json scripts and their functions can also be added.

### Reference
- https://github.com/LJOSC/scrapers/blob/main/README.md

**Comment by jay270804** [comment]
@HarshDobariya79  Can you assign this issue to me? As i want to kickstart my journey in OpenSource with this issue?

**Comment by HarshDobariya79** [comment]
> @HarshDobariya79 Can you assign this issue to me? As i want to kickstart my journey in OpenSource with this issue?

Awesome. Assigning this issue to you. Thanks.
