### ISSUE TITLE
API: renew access token using refresh token

### ISSUE THREAD

**Issue by HarshDobariya79** [LJOSC/checkmark-backend#16]
This is a sub issue of #9 

### Tasks
- Whenever the access token in expired, the **refresh token** can be used to get a **new access token**.
- There should be a route which validate the refresh token and send back new access token.
- If the refresh token is **expired**, send appropriate response code and message.
- Use a **POST** request for better security.

**Comment by AKASH722** [comment]
I can do it.

**Comment by HarshDobariya79** [comment]
Thank you. Go ahead @AKASH722. Assigning to you.

**Comment by HarshDobariya79** [comment]
@AKASH722 I'm working on a middleware to verify refresh token. Please check #19 before proceeding. You'll get the user object from `req.user` in the controller.

**Comment by AKASH722** [comment]
Okay 👍

**Comment by HarshDobariya79** [comment]
> Okay 👍

The PR #21 has been merged. Please take a pull.
