### ISSUE TITLE
feat: middleware to check refresh token blacklist

### ISSUE THREAD

**Issue by HarshDobariya79** [LJOSC/checkmark-backend#20]
This issue depends on #17 #19 

### Tasks
- A **middleware** should be there for the route which handles renewing access token from the refresh token to check whether the received refresh token is **blacklisted or expired**.
- Modify the existing `verifyRefreshToken` middleware.
- Send appropriate response code and message for various cases.

**Comment by kofta999** [comment]
Hello, could I work on this?

**Comment by h3110Fr13nd** [comment]
> Hello, could I work on this?

I'm glad you showed your interest. But we started the organisation to help out our university folks. And currently we're only accepting contribution from the University.
But in future we'll be opening to all.

**Comment by mansiivaghasiya** [comment]
I would like to work on this issue

**Comment by HarshDobariya79** [comment]
> I would like to work on this issue

Thank you. Please go ahead. Assigning this to you.
