### ISSUE TITLE
template: github issue template

### ISSUE THREAD

**Issue by HarshDobariya79** [LJOSC/checkmark-backend#30]
### Tasks
- [ ] Create an issue template for GitHub which have sections like,
  - Description
  - Current Behavior
  - Desired Behavior
  - Steps to Reproduce
  - Screenshots

**Comment by jaydoshi2** [comment]
assign me this, I'll do it and I have just one doubt that I need to create Issues.md file?

**Comment by HarshDobariya79** [comment]
> assign me this, I'll do it and I have just one doubt that I need to create Issues.md file?  

Sure. You'll need to create an issue template. That'll be created in `.github` dir. Please do your research and let me know if you have any more doubts.
