### ISSUE TITLE
template: github pr template

### ISSUE THREAD

**Issue by HarshDobariya79** [LJOSC/checkmark-backend#32]
### Tasks
- [ ] Create a pr template for GitHub which have sections like,
  - Issue reference section like (This PR closes # )
  - Additional changes (this section contains other minor changes which might not be mentioned in the issue description like small bug fixes)

**Comment by jaydoshi2** [comment]
assign me this issue I'll solve it.

**Comment by HarshDobariya79** [comment]
> assign me this issue I'll solve it.

Go ahead @jaydoshi2.
