### ISSUE TITLE
Add Dockefile

### ISSUE THREAD

**Issue by h3110Fr13nd** [LJOSC/checkmark-backend#4]
### Aim
- Having a Dockerfile or docker compose file will help people not worry about setting up project locally.

### Reference
https://github.com/LJOSC/community-manager-bot/tree/main

**Comment by het4399** [comment]
Hey i would like to work on this!.

**Comment by HarshDobariya79** [comment]
> Hey i would like to work on this!.

Please go ahead @het4399. Assigning this to you. I'm adding reference in the issue description.
