### ISSUE TITLE
API: Login APIs

### ISSUE THREAD

**Issue by HarshDobariya79** [LJOSC/checkmark-backend#6]
This is a sub issue of #9 

### Tasks
- Create a `users` collection with the required fields like first name, username, email, password, and optional fields like last name, date of birth etc.
- The password must be **encrypted** in the db to maintain the security standards.
- Create APIs for signup and login.

**Comment by jaydoshi2** [comment]
As this issue is already self assigned, is there any way that I can help? I'll give my shot

**Comment by HarshDobariya79** [comment]
> As this issue is already self assigned, is there any way that I can help? I'll give my shot

Thanks for asking, but since it is the first API, let me implement MVC. There will be more issues added soon.
